name: Automated Test & Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Pull-API-Into-SwaggerHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Check the API definition exists
        env:
          SWAGGERHUB_API_KEY: 5eaf7c4d-6a20-4e2f-8a53-5001f999eb20
        run: |
          swaggerhub api:create Adrians_Org/BankingAPI --file ./BankingAPI.json

  Validate-Design-on-Swaggerhub:
    needs: [Pull-API-Into-SwaggerHub]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Check the API definition exists
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:get API_Design_AM/BankingAPI/3.0.0
      - name: Validate definition
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:validate Adrians_Org/BankingAPI/3.0.0

  Publish-Documentation:
    runs-on: ubuntu-latest
    needs: [Validate-Design-on-Swaggerhub]
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Publish the API definition
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:publish API_Design_AM/BankingAPI/3.0.0
      - name: Make new version the default
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:setdefault Adrians_Org/BankingAPI/3.0.0
          
